### ISSUE TITLE
Stolen CSS

### ISSUE THREAD

**Issue by AshMW2724** [consteagle-com/issues#1]
**Describe the bug**

**To Reproduce**
1. Go to https://consteagle.com/

**Expected behavior**
Some origanality.

**Screenshots**
ConstEagle:
![bruh](https://legal-loli.art/lqukWC2jHJ.png)
Void Bots:
![bruh](https://legal-loli.art/C231xwOWSQ.png)

**Additional context**
My styles are ugly lmao (but somehow you made them even worse), i don't understand why people keep cloning them and making another bot list based on sank6's source code.

**Comment by janebd** [comment]
That made me laugh ngl... 

"My styles are ugly lmao (but somehow you made them even worse), i don't understand why people keep cloning them and making another bot list based on sank6's source code."

**Comment by AshMW2724** [comment]
You can see the diff here <https://editor.mergely.com/ppX8lsle/>

**Comment by LucasB25** [comment]
We have already answered you several times!
