### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by vspcsi** [consteagle-com/issues#3]
It seems like the scroll to the top button isn't working, I'm on opera (linux)
![image](https://user-images.githubusercontent.com/102188248/171866938-735e32fd-1ebf-45e0-9f0f-ddee3c711f42.png)

**Comment by vspcsi** [comment]
Well, since it's an error that occur on the main page of you website, I think it's quite reasonable to reach you.

**Comment by meliooff** [comment]
Sorry I didn't understand well, thanks for reaching us out x))
We hadn't noticed this, so thank you for reporting it ; the problem will surely be fixed in the next version
